language: java
jdk: oraclejdk7

install: mvn package -DbuildNumber=$TRAVIS_BUILD_NUMBER -DciSystem=travis -Dcommit=${TRAVIS_COMMIT:0:7}
after_success:
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - "[[ \"$TRAVIS_BRANCH\" == \"master\" ]] && mvn deploy --settings target/travis/settings.xml"

notifications:
  email: false
  webhooks:
    - http://get.spout.org/hook
    - http://n.tkte.ch/h/1148/c1ZbS3rufJyzaghnxyW5Iu5e

env:
  global:
    - secure: "RfkXqulUgAeL5BSzWY42nec2xSTFsPi8/SPFgUeJ4qM7OXsDAl2CR/XUwW4YC5uGM0Gq1x+kKXph5/OXmovIW62YLvfUGTdEmEjTSGnwSafAxzVoHbV8glfo/0SX5CaQeZQvbRR6gJxSiNUWJGuiA3UbW3UOMJHKNaWOi1HMf48="
    - secure: "AjQ7sIgwFgicIvFZhRsn8KkA4H2XWEsIDH+QjRTLpOj8eoPcKP/IcfxH8X8KRNBJK/g84K+8YdGCDlZ9QJz349BI+Jzchp+pBAQyau8wK3nR1yerhOxFLwbOB7SdW/rMj+AfufJNq4QBzwjs1b4hoO7NRrmdb5rgbGfu1DeOFSE="
