# Source language and JDK version to use
language: java
jdk: oraclejdk7

# Compile and package JAR and set build properties
install: mvn package -DbuildNumber=$TRAVIS_BUILD_NUMBER -DciSystem=travis -Dcommit=${TRAVIS_COMMIT:0:7}

# Perform steps after compilation/test success
after_success:
  # Get files for use with build, namely the custom Maven settings.xml
  - "git clone https://github.com/flow/travis-ci-resources.git target/travis"
  # Check if commit s not a pull request, if git repo is official, and if branch is master. If checks pass, deploy artifacts to Maven repository
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == flow/React ]] && [[ $TRAVIS_BRANCH == master ]] && mvn deploy --settings target/travis/settings.xml"
  # Check if commit s not a pull request, if git repo is official, and if branch is master. If checks pass, update gh-pages branch with generated site/docs
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == flow/React ]] && [[ $TRAVIS_BRANCH == master ]] && chmod +x target/travis/update-gh-pages.sh && ./target/travis/update-gh-pages.sh"

# Notification services
notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false
  webhooks:
    # Send build information and status to Notifico
    - http://n.tkte.ch/h/1148/c1ZbS3rufJyzaghnxyW5Iu5e

# Environmental system variables
env:
  global:
    # Make the log output cleaner
    - TERM=dumb
    # Super secure, encrypted variables! Ssssh!
    - secure: "bZNAAo5zzbW7QdDENi3SC1iZM4aoa8ppke/A0BE4IAlug/G+0bu3YEYrWFgHM6fm6FyOslxc+XEMej4hfHd+Lmj4wXiFCKUfJlqE6AQV6yyHljQrjdkBnQeWiLdWX1oz9UjxdJpEFuGrSFZ9xW3fKnWfDgDT47rTAGK3VbDrkz8="
    - secure: "DfECXrCJyKdNVzsO2LMMMyHA3F9vFwn0g00kxM1zCllpULmSQgH5GzxqJOAqfWdx8F9kQOrRcxsBz5AqIxZ+rBrYaDJTM20ogMbiy1zcAVt+2qUfl1H5hKSQRCYp+wwRzMUpet0/t7ANUAQVfbZx51oocPGAJZQ1XpWGZfpAQ5A="
    - secure: "KLGHvbSzebvL6CVFMexEXsLCKhkEM4RexL/e9WgGtnvtsXQ/Dtz/VVMAJd9YCS/sHIgBYW+HRGO7NOA1b2Loc7qDGjO21oOuljswCKiwZ/lytpaJ0s8Ygp8SGHMdoHJg/lvNBoI3u9kMYNtzZeFRJMTdfMgjwz3np6YIJ7V2anw="
